name: SkyRL-Train-GPU-Megatron

on: 
  push: 
    branches: 
      - main
    paths:
      - 'ci/**'
      - 'skyrl/backends/skyrl_train/workers/**'
      - 'skyrl/backends/skyrl_train/distributed/megatron/**'
      - 'skyrl/train/config/**'
      - 'skyrl/train/trainer.py'
      - 'tests/backends/skyrl_train/gpu/gpu_ci/**'
      - 'pyproject.toml'
      - '!docs/**'
      - '!examples/**'
      - '.github/workflows/**'
  workflow_dispatch:


permissions:
  checks: write   # for status checks to appear
  contents: read

jobs:
  
  skyrl_train_tests_megatron:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install basic dependencies
        run: uv pip install anyscale==0.24.79 typer==0.9.0
      # Run tests
      - name: GPU tests
        env:
          ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
          ANYSCALE_HOST: https://console.anyscale.com
        run: |
          anyscale job submit -f ci/anyscale_gpu_ci_skyrl_train_megatron.yaml --timeout 5000
          anyscale job wait --cloud sky-anyscale-aws-us-east-1 --name skyrl-train-gpu-ci-megatron --timeout 5000
