name: SkyRL-Train-GPU

on: 
  push: 
    branches: 
      - main
    paths:
      - 'skyrl/skyrl/backends/skyrl_train/**'
      - 'skyrl/skyrl/train/**'
      - 'skyrl/tests/backends/skyrl_train/**'
      - 'skyrl/pyproject.toml'
      - '!skyrl/docs/**'
      - '!skyrl/examples/**'
      - '.github/workflows/**'
  workflow_dispatch:


permissions:
  checks: write   # for status checks to appear
  contents: read

jobs:
  
  skyrl_train_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./skyrl

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install basic dependencies
        run: uv pip install anyscale==0.24.79 typer==0.9.0
      # Run tests
      - name: GPU tests
        env:
          ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
          ANYSCALE_HOST: https://console.anyscale.com
        run: |
          anyscale job submit -f ci/anyscale_gpu_ci_skyrl_train.yaml --timeout 10000
          anyscale job wait --cloud sky-anyscale-aws-us-east-1 --name skyrl-train-gpu-ci --timeout 10000
